---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ddns
  namespace: argocd
spec:
  destination:
    namespace: ddns
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/smart-home/ddns
    repoURL: 'git@github.com:LukeChannings/kube-config.git'
    targetRevision: HEAD
  project: smart-home
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
