---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  local:
    path: /data/config/unifi-controller
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - suplex
