---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.10.10.3
    path: "/data/config/unifi-controller"
