---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config
  namespace: unifi
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "local-storage"
  volumeName: unifi-config
