---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: poller-auth
  namespace: unifi
spec:
  encryptedData:
    POLLER_PASS: AgBBEeoERf+KAahGY9SPtm850D0gCiqv9mvmzmx5AtGrYuzMBpmoUStzSYl0Oz+aw6wa5E1EIgTm50Ts0UvG4jOjKUPMYTmdeWigCFgNfbJyZsL1Fi9sn1iUz/VtyTvTVuuA8g1b7gThkzkpvDNMO8Al9/YUlPNydbjzK210sVFHY5Wru68PYBqKZUgS/5wPmDv1m22+AXMoJZnptxfSyWLUYkTmzjjQqEXUnoQ+hYiHxvGIbep7pwHuFPGrabO/g1KSH+K54IWlsLbLHl0MM02NrNi1uHGyh2eyGCI0M4/YjyXi6UwemMZT+zOh7PIcSC8NUaro3GRmdYTckYK4IOWcsvMVYOvM1bRafb7Fm7DiuyTgTbK58blmj8PxVogKIOkBLrjJpN455QAJFLrDaxldGc3NUvmj8hfGBvfz9KHvv/+Bv8eK+isHKR5jy2AA/ZAUV/i64QDjQbRAeJLoAuf8lcVMW5LsEqylW7a8LsxKeGHWvaHJpxiKGX43KfH3BUPUsZPeLOd8x83t4PyuSj/XsAPo5a4whMqOXWFFdN1rokQ1fq9FwE7oXEMqRuDPyNXvTXD6lvw3ZuAATaPGwiMioAHFzT6LSBMKBJ2N+FwEF8Sczlr+h2nxZNAQSQ6hdkSpk4qxhkP3FVVcyRQ62jQTJ45s56QCyoKoe2RXus4IfW/Sxpp7YE6LGqN5Qyv5YrULL1IH83unore6d2Ow1ah71Juc4eXiCYzmmZ2jyy+RqUQDp1GBXOzu
    POLLER_USER: AgAWRoIUMO7fpMh5G6WdyS4XAMuRarCTV9zjFQJNLZKtVN5fpwFiLDetIGT1pdYfSL7864QwW6FW0//ZGUuKgu4Vw1cpKNV4Z/f1QN2A6NdhnktQbPDMkkTnxSZEaxRVtctubTf+b1SgDO3kbUtydLq8WhkMr7ZEMtP+uUwrQR7evhUUE9N3p5LQSmbQSvHRqYU7OnPvMuZ6frJU12ckFVgZJ/MQd2xaA/FrkxEHWvSiaUn+bqtQLle8Ff43lvY4hNsTg9H2rtojOsPsfTH7fabj85CJhfQ2QGlsHkfF6Sug4nwwiVJBSx8y76DvnJIDNfWT1VA7FiKOLjS6gdPjprxzEiou8ceVkPOUYJ8uU81rQ4IinH2bAoXoMPGjjsLeI7GKlcPxs4gXO+iAzsS7xgUIa8OyjwZ5engSqwnAQHaI0BpCTv074kYOPZbEL4LgpXsi5k4Kom6hfQBnM64pPwP/fplrVPC5+rtZDlNMHcAAODs7Wo4yl7j5/gXJ5wax9wy0Y2TAsj28aEYluS+onFBzt2o+IrN89eb110QWhxfY6f9mcdX6fOlL4zMzGj6kjzEg0Fnay1cUs7e5vWRJfpTUfuzqBZZT9zKCic0SQFShmuIP+DR98G6VJl48t461MJSWapApnvX5fuLlOokxcYEH28w0GTCRGJqLMsb4K1jjEOZMlkXi5sTdmXEQLLY4vhFCVIdTiwrMENpY3A==
  template:
    metadata:
      creationTimestamp: null
      name: poller-auth
      namespace: unifi
    type: Opaque
