---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: unifi-controller
  namespace: unifi
spec:
  endpoints:
    - interval: 3s
      path: /metrics
      targetPort: stat
  selector:
    matchLabels:
      app: unifi-controller
