---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-home
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/smart-home
    repoURL: 'git@github.com:LukeChannings/kube-config.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
