---
dependencies:
  - name: home-assistant
    version: 0.12.4
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: postgresql
    version: 0.12.4
    repository: https://charts.bitnami.com/bitnami
