---
home-assistant:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      ingress.class: internal
    path: /
    hosts:
      - home-assistant.private.channings.me
      - home-assistant.channings.me
    tls:
      - secretName: home-assistant-tls
        hosts:
          - home-assistant.private.channings.me
          - home-assistant.channings.me
  hostNetwork: true
  git:
    enabled: true
    repo: git@github.com:LukeChannings/home-assistant-config.git
    secret: github-deploy-key
    user:
      name: "Luke Channings"
      email: "luke+k8s-hass-sync@channings.me"
  monitoring:
    enabled: true
    serviceMonitor:
      enabled: true
postgresql:
  rbac:
    create: true
  existingSecret: postgres-postgresql
  postgresqlDatabase: home-assistant
  persistence:
    enabled: true
    storageClass: "local-storage"
    accessModes:
      - ReadWriteOnce
    size: 30Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  securityContext:
    enabled: true
    fsGroup: 1000
    runAsUser: 1000
