---
home-assistant:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      ingress.class: internal
    path: /
    hosts:
      - home-assistant.private.channings.me
    tls:
      - secretName: home-assistant-tls
        hosts:
          - home-assistant.private.channings.me
  hostNetwork: true
postgresql:
  rbac:
    create: true
  existingSecret: postgres-postgresql
  postgresqlDatabase: home-assistant
  persistence:
    enabled: true
    storageClass: "local-storage"
    accessModes:
      - ReadWriteOnce
    size: 30Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  securityContext:
    enabled: true
    fsGroup: 1000
    runAsUser: 1000
