---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: zerossl-production
  namespace: cert-manager
spec:
  acme:
    email: luke@channings.me
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: rFF9EQHaAtM4lcE1s-UqPQ
      keySecretRef:
        name: zerossl-api-token-secret
        key: external-account-binding-key
    privateKeySecretRef:
      name: zerossl-issuer-account-key
    solvers:
      - selector:
          dnsZones:
            - "channings.me"
        dns01:
          cloudflare:
            email: luke@channings.me
            apiTokenSecretRef:
              name: zerossl-api-token-secret
              key: api-token
