---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zerossl-api-secret
  namespace: cert-manager
spec:
  encryptedData:
    external-account-binding-key: AgAR+wmZnlBEmlsSi79UfesKopq7suwldYqV4WXpaE/uj8z8GFZ6qDBD9XxY2VT9btsn68JnBJLBBDP/Ze/4Lz/B0W/kuk4+pnRyhYZHdzcIRkni5QCJiVGKjq+1+3OMEl5yuMmFpLc/9Ukjn1PoKgDiHchan/NpzWogNfrXFwEHZlikcAmDzLEXUI+VOImsPDFB5/4fd45YsYWZmVpOeqmUnZHwCDwlw290XSTmo3Qrb5CHtqc3kpO4hfcjJqVnsPETyt720Ow6gtWjedRivu+lGptMI3hPWeH2g2vw0gDJCEsbQ2xNhlgPniSuaDMgnbRTJVWG/1L1OElfsKdEXMFTawHKCa0O9b3XVlAZdoGdf4X1nRuVDKbQglc5NRmriScRwn+1mhLLBZEPvEfAv7ZPt6/SxRKQiyO264/V0mMn6ZSY0QPZ1LVgnkPnHvEJ9nWUH5EavPTlDmVbGdL4btPtOtGuTdWdiBHtUz+AKbEiJ1Q2qdD1WAKtkWaLiSlNkRfiWaGa7qb5FDlLfPTQMn9DBcyvNHBwYOGz3IiG6LYjordE1Fv/8S8QhUQ75k5+1FBut48rCivfgfamM0gzfhfpVhtJMqsvttGiK+SR1UC2j0NdqDyXmGaMEbC3ISzJHesKFORFGwAY9tZvypRmnCE28IXW9Hd7WGVSHVFPjHElDIo3DRbBj9s+oqFfDprlsQweSjhEsrw8e2bPT61o/jBxjm7KDvOsRCiQA3xw6NfaK+kZ3G79kPGRhmUxL/Pw/ATaQ7BnOeca0hSD960siVaPnqPr/5JGvowWJgudrN9uawQs1en1vA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: zerossl-api-secret
      namespace: cert-manager
