---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zerossl-api-secret
  namespace: cert-manager
spec:
  encryptedData:
    external-account-binding-key: AgAAZ3W8oNkpAmmVVZ4NbOK37jjig9pIYOBd+QMaCmn9H4XwrNOhv3vqKmS4uO/pOaFC9GrpoMvEFsnDeuqS74LcVoNwj0JDTBB3Y5xokVUJiTyLUTGW/XQSpzQ45SHl6PpfTS/H6OEX2InmB/Z1rMhjDKvV+tOkMZ8s+qMuXUKfoO/k1r1bFxaZPyhNDR8pZKAh9AoJn8ehSpDJJIcLsTbANrAINE6Gq7t63dxHqV2tjbL79jwvD0xUQu1AEmXbV/p0TJeJPlILUsej16496j66q3uJJFCQeBzSjpLFOsodi3yjLiWJruQQvh572rS0Aq7Xtj8S7/iNu6RYriDGxyw3PV1PylVx5tXFtV2V7ll+dpL7KyK5fr3zf5cRCfttIrnTrgpCU/CeFXIcGoKa/nhyXs6XnaMmR/+Wr0P8cPbBETtlqZVia9uCSJddRkpTyubZt7480pXRfhyBMyqIsoR0pCKUUlanbtf1HFFB6Aa/e4D29tzB2Z2AzLVRvJrxIr6VVszq+x4QfvEqKbOT9R6+dpaYNZBi8Lakwg+D8dQI8+N8QdcoJe8AyAt8ZMllNIDwxjI5obeKqXvhMXsEyob4a7NiIfi7aPKX11j1xrAt2GyJmQp5ouCJC6yBsN+s5UXk7+0uXHMtxroXC/8t/KJSacHDBtve12IGWhE3u5FvrsK2tfICOibzTwwrlD19/J8A6bhip5BptHa47u/hcQrEHaxS6gkpivPOElUdRqonOjM1nJc3cgJANZKgyNR8CvLnt0rH7Cjp+QB+oBC72MbZpZ7++1KWXx2OuHrvOel824W0U13TCA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: zerossl-api-secret
      namespace: cert-manager
