---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC3bWA0zAkngyBGilI1fFJraetkavpD4c0DAgANTHKDhZy0Pff3B7ACPRMhcsMWwZrivawhGPP/lWHdd/+oIXPUi7y8tnhcJZmBdn7Z+5SAgmrTezcSKJSfc0Pc0IF9Mr0OXoveU9MomGJbApf5MOuNEovtPfHaG2VrbLppNm+QIHgAutM7M3Vm/6VVUDUU97N4+gurktKjamBZhLQCNFeyRPPqnjFLOTDagFpmVtGP4rJWjqin8d9tD2nUu201Ir7y6E9zKdIG0wOpd1JdTXWSZmcHihZMmpc9X5U8trXvLJHs1g/aoq95yntp+0Qqk2sMYh1QVUD1DFwo+wVDnmBEjnNVomn7aAtOlg3ScVlac2RhwsQGgzP59gTcGbBA28UzG8FQLYlICZw/Dc0Y9SsGWv0AaDkU6BzYaQhevAwycmRzVrwJOwKCCDsRjznjRGz0GCt9cbqTJPZwLiXHxjTas10U/pyGEt79jpKdESHxkrKAPia0YfYlGjaYXehorUqKDhHlQ3I51983dBLHCL1fkpKBXVKjqgDKK2tgtmwsOYTCxuPaKLUoTEHaSJowOC2lpOk4V/GrnRtNkZ/EThqMI+zzqyXyMMA6UhsbZo+IZeKLMWtMXMOjHTL8XfUXaM0bo8kQcgMYRTIKDiSXHJc47ED1s5MsKL2FCteRmmiVecTIN762YP48lR2JTGR23ClXSpqyXtcYklrj400zZXff3v/qXSxwag29VUWsGLRRd+QuOTwB2WYb
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
