---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCuVOnlwxBKHutRKgg6Ds1dYGg/FKGkzsRp7Yowrkb/C3Py73VGuIFUGxxuT7lZ36bNuEDrc3pPqUWEOO/fdXlKPhhBpz9QKP6LV25q8NANFMxrbIW3xZg7N/+3E/VJZIIy6KAB4yoYcATYfVqyope/90dyH85j5f/a3g5GMHd4o679X4h+BTYa+XLPF3Rd4SwE+GjGiZo5NXvGKoc7adKVDIJM9I/KyyJAs0JuFpM2G5F0JaqLWY7z6ir3QfF++hlSDTWNuz4qYwRpb3G4f8MjZNSffy2qKUa8cUUoSp0U1JXhvp6W2YCJgK9fCmqYLR4jyw4HKz5nkkZRIVfbv0iv02dPbwq+TmgxRGtzAbxzwC+2uYjAvgKpHBQ1aE6Vl+EoQT7Hn0UVWrPp6vNafvj8vzOAq4srbpqjLJcAKPPzU2wCLLeeqbL2Pj7QK1Fhpv2PsY1m7NPbZPYWi/cMMbOKCVNB/DhRX8IKniLMjsdm+NF8NdWoOKMsTWEgOQiEASAfLRGcgcusp5nctgE18bn/zeRLXiFumPBBvewEqpfAF6Ae1ganyjbewXlwY7dmxRe2KMOmgSV9hEmvY8nkZ6ADEaMvzBPwfqFfh0NBEW1+6AX1kXoINGChLAcYCxd6JbQuJXEa7A0EDCkWyOA6dw4yjKrFUqQzLHoyUZMkMyK2/6lHM7PEksbyNEZ/C5/GSA44X+UuQv+TRgotgSJo005ICrwfPAhGWM0aFuYhcv21v80n7ycRBb9u
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
