---
internal:
  controller:
    ingressClass: internal
    defaultTLSSecret:
      enabled: true
      secret: haproxy-ingress/haproxy-internal-tls
    service:
      type: LoadBalancer
      loadBalancerIP: "192.168.1.200"
    publishService:
      enabled: true
    nodeSelector:
      kubernetes.io/arch: amd64
  defaultBackend:
    replicaCount: 1
    nodeSelector:
      kubernetes.io/arch: amd64
external:
  controller:
    ingressClass: external
    defaultTLSSecret:
      enabled: true
      secret: haproxy-ingress/haproxy-external-tls
    service:
      type: LoadBalancer
      loadBalancerIP: "192.168.1.250"
    publishService:
      enabled: true
    nodeSelector:
      kubernetes.io/arch: amd64
  defaultBackend:
    replicaCount: 1
    nodeSelector:
      kubernetes.io/arch: amd64
