---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: haproxy-internal-tls
  namespace: haproxy-ingress
spec:
  dnsNames:
    - "*.private.channings.me"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: haproxy-default-tls
---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: haproxy-external-tls
  namespace: haproxy-ingress
spec:
  dnsNames:
    - "*.channings.me"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: haproxy-default-tls
