---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-config
  namespace: zigbee2mqtt
data:
  configuration.yaml: |
    homeassistant: true
    permit_join: false
    log_output:
      - console
    mqtt:
      user: '!secret user'
      password: '!secret password'
      base_topic: zigbee2mqtt
      server: 'mqtt://mosquitto.mosquitto.svc.cluster.local:1883'
      version: 5
    serial:
      port: /dev/ttyUSB0
    advanced:
      network_key: '!secret network_key'
      pan_id: 0x1a67
      channel: 20
      log_level: info
      cache_state: true
      last_seen: 'epoch'
    devices: devices.yaml
    groups: groups.yaml
    frontend:
      port: 80
