---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
  namespace: zigbee2mqtt
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  volumeName: zigbee2mqtt-data
