---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zigbee2mqtt-secrets
  namespace: zigbee2mqtt
spec:
  encryptedData:
    secret.yaml: AgApa+gxJ+sRZXwrlpruVeKMhun0QcAgKatCRM9wKIjjZMl3/fXORUphbqkOK1UfOv/zSDF05hcxS78p4pODApBfCuBe/bOvYtjYV1vCq8G9DiZxVf78009PfLUn6nM3XAeriljDnPPLTEJVkwhvoGOi9Ut8uodayzvsJzv12Fu2xV5PXlLhsmb2i0UBfMN1t3HdeqgS6VoGrQCHujZ2Bt2WLOGerxeeQv025V9CSvGbVFP4+gXN692ywYLbKYCU75CnxwleLT+lSDcB5ItqwO260OROddwDipc4lMe9CzxsadbaJNykGtETG6g/0l2xIC6vOwxEjP0tF8YktYXpqaLhiu0t9wXGp53SQVmw0hPFaJx2sfzXR8cpbXFXxXo4XRRVyY6NwAHpPShB5P7u7PxRBofAgZwyIgQ1JAKMGrzyFT6NeBjYFEP93a7vw8cANM4Q9Izkf53AhQFggnPaJBoRpsHvkub6rMShPHmccrHosmXFYZGgHSVYw9iq5ldZsmEv1GpFMxMWt+8xAg165dgykooUWNjKxnocjn9ODJwUfUtzwKx16JaNmw3q5+x86chPQwE7a8bUbHPxQ2XmAKri2SWhzETN+Cfw8W0lZj1u0QDYx1pL17URIbGCC+ZbSe2nWmqOp7vimFmD5WyyjHR+/X3R/XqLOkPMQAKWXHo/U95yTljitW0bvlhclNMZTWYVtOUAte7YyjjBwUhzIc8CDGzlnzjZhUpprwuclin389n8Tae8haEzarr0Nl5ImhQkjcubnWReleKs1lkMtjIuYACZV2xJuovqiczDYD12Ekhdhharh95V0oJOsQmItdIPhFw8BmaJRgyJeu+AG+4zMKZu8dpiz+I1Ipl9cNC5/2vUO0ssUw0Wy9H6+vfQMY/RXoc=
  template:
    metadata:
      creationTimestamp: null
      name: zigbee2mqtt-secrets
      namespace: zigbee2mqtt
    type: Opaque
