---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto
  namespace: mosquitto
data:
  mosquitto.conf: |
    # https://mosquitto.org/man/mosquitto-conf-5.html
    # https://github.com/eclipse/mosquitto/blob/master/mosquitto.conf
    allow_anonymous false
    password_file /secret/password
    acl_file /mosquitto/config/acl
    persistence true
    persistence_location /data/

    # MQTT
    port 1883
    bind_address 0.0.0.0

    # MQTTS
    listener 8883 0.0.0.0
    capath /etc/tls/certs
    certfile /tls/tls.crt
    keyfile /tls/tls.key

    # WebSockets over TLS
    listener 9883 0.0.0.0
    protocol websockets
    capath /etc/tls/certs
    certfile /tls/tls.crt
    keyfile /tls/tls.key
  acl: |-
    user luke
    topic readwrite #
