---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mosquitto-password
  namespace: mosquitto
spec:
  encryptedData:
    password: AgAZs+9Ol6MDQ7ftGcOhBd+KRo1fAYLM8nYDGEMDptvpVqAQFeIoBmFI/DvkpUc+u0FrL9FcGKiTSgaPtcqRWlmv31eT5tGnSfR6yDP0MVEWHH1hopQzq8tRcOYopHu1EPE6WN47/B7NjvYeG7yHcKTMUJMxi+1dkAh2R0/lU9Ska2zZdpUXOqDZCzE0B5eo5p9KvLe2GhQegXi5D6DvkKE8MbwTxVEjzqPQ4ngbBxg9Huh1nyoviVKXOC2CPn701egdAGDM9GxZ6K3TPbBt+8iIthp1Bm8IdTvWrB+fNUuJGompD8MKRgz/XzIq5Vd6BxGvDP3uEpQc1hBd9TXvxDltHdV3cYmmcS40aUxelJgEyArLyDeKVpecz2KiDBv4Z1J7Xe0+vsWG024yYH40ejcbImJAekhjqafkVXWxVNXeUpJ7qpOUUfRLdafYBRlAETpDrgg/0aQ6LwBANQU9Yq21zZIkhTxRG3OY5RUg/katqAX1qmGkHHs00jRiBSsjghP8Lzaj9Ee3+vSBMkfyhpwSpByC2Ezo+EwD7H6L1A6wWnrco64I0rZWMUd3AQM71ODBriIXscvUWnpPWwld8FB8VXjpmPEw/fkWhAKEjLgwYw7JGNlPy/mGkMHGaWVgXGBSzEPgq9pTiTXS2DF4H8e7FahWkgX/wLueZ+T25TiPCZTD80ZxfdSE9vGyseWJeGo8lB7q4Wa2jgk7Ct7lWALQ61dX20IQ51Zj6xwUp9yOYNMnyuCSwx+VQ3HudiDYV02Xld8cH0YhR8iZv0FJCttCGGG37ULUMlEaPTuBmOYA+NBJr+BwVmDPxfoohMr7UA8tKsfnd9KANecIpI9pmPzyTw==
  template:
    metadata:
      creationTimestamp: null
      name: mosquitto-password
      namespace: mosquitto
    type: Opaque
status: {}
