---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/infrastructure/monitoring
    repoURL: 'git@github.com:LukeChannings/kube-config.git'
    targetRevision: HEAD
  project: infrastructure
