---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: sealed-secrets
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/infrastructure/sealed-secrets
    repoURL: 'git@github.com:LukeChannings/kube-config.git'
    targetRevision: HEAD
  project: infrastructure
