---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: node-red
  namespace: node-red
  labels:
    app.kubernetes.io/name: node-red
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: internal
spec:
  tls:
    - hosts:
        - node-red.private.channings.me
      secretName: node-red-tls
  rules:
    - host: node-red.private.channings.me
      http:
        paths:
          - path: /
            backend:
              serviceName: node-red
              servicePort: http
