---
installCRDs: false
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  service:
    type: NodePort
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/ingress.class: internal
      haproxy.org/ssl-redirect: true
      haproxy.org/ssl-passthrough: true
    hosts:
      - argo.private.channings.me
    tls:
      - hosts:
          - argo.private.channings.me
        secretName: argocd-secret
repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
redis-ha:
  haproxy:
    enabled: false
