---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-postgres
spec:
  resources:
    requests:
      storage: 30Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "local-storage"
  volumeName: home-assistant-postgres
