---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config
  namespace: home-assistant
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "/data/home-assistant-config"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - snowkube
