---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-postgresql
  namespace: home-assistant
spec:
  encryptedData:
    postgresql-password: AgB8aL9VSeRfHuboqEW7zzzMCWO6rLhyKLPGBuF/G+V6+yN0kHjAZ0VromPzrfMfSO+agk2an0sN+URf9Vg2F/9qEt0NBIK0kkDSsSysdaQ+aVRVjCMI9T7D4c7dg9LQ/OpQJ7fIGVIlJmO9uqLXdQIMmtup66JYgaoYpmT/dNh4EV74wJl/Oz6Oq8BWyQgvAms9yL3xWxBDMjrD3dTSCnCuBbwl2s03onuqBwuS00ZEGmar0zX4EjJNiUpGhnmF2AL1e2w3OUkuNgw4g0chmJSJVZ4HDe4N2mal4heIliBU6lxp604frjashjujeHzV4Rsnz75AERHI1vnMWAyWhgOJ/6Kp5xbGgEw+VUU8GesAqr7ra8eS5r7oDyRPujN5zSNjurGB3talx5rpaEds03fxJ0/EG6TmYrcMH95n4E+MSRXPUiUm4GuSJPhmYYIxLx4FgLibI7N+ljTerzjeqfoYaJvysVGyW2af1pTBP43oFoPMoPb8+R6o7RhKgAo/sEHPPcd3B5jcJwCVP7cGIJ+LsCYCvLPS0Xg07IB25NOPvRKIuPRvFAYb2m1qeFEKaTRswjeUVibdoCr6kZOFT8gmeI4/RQyf+iBCZcj+fqoA1+LMEzX2LdwnzvTwM+WcruaVzZ5rRBMbbgJpdjo0Z3y4P5Z3cFgv1mohaj4X7XSbz49/LbelYyBkrCShrVnShso0CzoviXSn1OUlLQ==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgresql
      name: home-assistant-postgresql
      namespace: home-assistant
    type: Opaque
