---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-service-monitor
  namespace: home-assistant
spec:
  encryptedData:
    hass-token: AgBbfRKz8yTYeDNngHGvKdLfXJxmQ3QpcrTpS2CPs+Wh3LrgLkVNfPnQwRL7ovgJKtyXbx8xPaUNGm0BoRsoI4U8NvQQzBJB8YNHfW0cSGMBlJUB6AZiY50Nzrd44tUYOx+AyPrDx8+JmCUCzi7TuUShcMxJWx+m5XkZzYM3LBv4YLPheIiH3nZ2DvfGN5CFWKV8LnGBp1irjdcFW/cDsr4z+BJr1JoVtX0E7B/IN0xrqDKXUQ3wO39bowIxt5dGiaqi7ppRE/j00Rh3SpDktc5aKkuqkjbrPIgc3X8OhgLBe6KMXD76L3WlTi4Nr3cBS/Yi83Z2kFVr3K5ENakbUlO5XnunShH/3wWTcvCH6W2N4jw+Ngtdtu8mF7g4mHMeoCu1ahzKPVfM0RLfUSN68jd56eSE1D1jzteayoaOr74IzyXQy1XK/N+P3YC2ATaldXLa168TQGoUPBSnGTzrzs/XI/+oo40/pmIdo6q/jR2fdiNMlRpGeJCVWrlRnSvVkmgER/FUMqbltWgGVX0Rk4lQLdB2v08kOC3RLEeHIiD0cTbTcA1h+x2TPMdLzKPUAg59o3Pm0FuuhAUil/oTL+W+ERcZr4q9/M/KZWtdpTDMTpWiQV41ZVzCi6vCMNzGGHYMfDAcsyQ74mYNphLu8yymsJsMc6ricPxtMP8WCj3FJ0jbeUsGDvtYqfDwzv/Sw+OLqftRATNw8dx0ykBTEYxqlztqtj9/FiJcG2tPGhYu12Q7Lw3R+wmzRCNxL4ek9u0NZ0aIPoBKxJiJrcwqs4EnnbPxgKfKcfohZEMBxGJI9iGYBO2Ux+kU7QnYdqlUio+7Z9Xd40DmAbNlZdcP+OazFhGDXW3S+GVwK/wZjKl5bcus38RRkI2Nw5hABfpJz6EOkrTV9ZIEpX4JmfAwkpbFZHYIsIfunqK0pnNOqQaFqmYDLE5/sjY=
  template:
    metadata:
      creationTimestamp: null
      name: home-assistant-service-monitor
      namespace: home-assistant
    type: Opaque
