---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-postgresql
  namespace: home-assistant
spec:
  encryptedData:
    postgresql-postgres-password: AgCa5LreusIeckXMho2PVLc4Jq8rIPoJJ188igoCu/Us/Tr9XKV92u7YiqHf26MNp2HK9dF7k9a/Is4Y3szBYobAktO376fm+pCFor6mFZefDSt5/8BJhz3nVgviIL6SLegFhLm4aCdS+vPaWESu9Zsl9ARzyx8sl3frogDomCKc5/Jy1VfaA8mCKrNSy2S1pGvDw8gup/h+sOiiioNQj1+6CT7LBm5rp2mfxWB3IDtOI2RpAzG4p3pM1CAS3t/C76kNwBzYee3pQ9ZCmuiKhm4t+ELSwUmn7kFdvwapC9rwJICspYXJu2QTlhY9pHKgnJM/0xrTCa9Q5fq+tAbEv7m60rT+fI4Qmsu7w80TL86TCEA0rh2Wtpe7Lw/ekDt9OUjah7nyXhioWX91vhnX8kaaxzOxaYh/ZdToMvgRWy+UrlmqswEEYU8JqO27UPF3RFljAn/gNcNZYBXUlXnRIz+G43+fb7qVTxumLu1/y72/+bIO8aq8X0HFp6ssbCfvvWNAVsy7X54Gjgwe6Q1sGt6IUeeyojXfpKnpvyy5ra4I+c1+HCDXoYrHZWZF0A6MxsUbPwC/lp1ynwsfjoGYWaeZNIihDcLgSQXNrO70jc+PmhmvBeTr+r5a5aOrm1V25Tm/UNp2/PUwULUpMoHqlBP/EjcCMsBTwHV+6HyxmZFRnDfx0UwnsYbLvJEGM+QfnNYHN5HnsxOR+d9BWu/ipkC1FZT6la2DLgJDw6gR7irPb8p3N6OTNClNWQ==
    postgresql-password: AgCa5LreusIeckXMho2PVLc4Jq8rIPoJJ188igoCu/Us/Tr9XKV92u7YiqHf26MNp2HK9dF7k9a/Is4Y3szBYobAktO376fm+pCFor6mFZefDSt5/8BJhz3nVgviIL6SLegFhLm4aCdS+vPaWESu9Zsl9ARzyx8sl3frogDomCKc5/Jy1VfaA8mCKrNSy2S1pGvDw8gup/h+sOiiioNQj1+6CT7LBm5rp2mfxWB3IDtOI2RpAzG4p3pM1CAS3t/C76kNwBzYee3pQ9ZCmuiKhm4t+ELSwUmn7kFdvwapC9rwJICspYXJu2QTlhY9pHKgnJM/0xrTCa9Q5fq+tAbEv7m60rT+fI4Qmsu7w80TL86TCEA0rh2Wtpe7Lw/ekDt9OUjah7nyXhioWX91vhnX8kaaxzOxaYh/ZdToMvgRWy+UrlmqswEEYU8JqO27UPF3RFljAn/gNcNZYBXUlXnRIz+G43+fb7qVTxumLu1/y72/+bIO8aq8X0HFp6ssbCfvvWNAVsy7X54Gjgwe6Q1sGt6IUeeyojXfpKnpvyy5ra4I+c1+HCDXoYrHZWZF0A6MxsUbPwC/lp1ynwsfjoGYWaeZNIihDcLgSQXNrO70jc+PmhmvBeTr+r5a5aOrm1V25Tm/UNp2/PUwULUpMoHqlBP/EjcCMsBTwHV+6HyxmZFRnDfx0UwnsYbLvJEGM+QfnNYHN5HnsxOR+d9BWu/ipkC1FZT6la2DLgJDw6gR7irPb8p3N6OTNClNWQ==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgresql
        release: postgres
      name: postgres-postgresql
      namespace: home-assistant
    type: Opaque
