apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-postgresql
  namespace: home-assistant
spec:
  encryptedData:
    postgresql-password: AgCRaQN0KFhFpzL0zKQAnmXYyhbx96PgjMrao4vFXyDJnIZuTMbD4ra4F4qJSPpQUI0RNxYorRZYXxYrZlPHe9sffvyg3uPrGLrKeDSpI9GipEHJFAnx1pWsq9lSGKiA++8hXC5Ic5uhABeoN6yHYU1Efx0E4D8cy483ij0caYXTLTTl3yevY0kVu9FRklx/CkRLIP/elXXm9YJcgzio02J4TXdu72UNfmbEXXAggtsrHjjDhSyFF+PCEgg5gZX3XnpGLBvWvuxquL+tB9r+0BuYOsmaiSJstaiFMwQG/GLJPuHqlO9BwkVIzjy9+63aZOCFCBcO205UbB/hn9JS4541sb/KDlRWWloGVDKYE82fF+pdBEXSzOi5nUD/jVm3N86jD/HHIm7WohHLtIB/Zg7Mjw1hL1/0bB0kuEEUENMFv3ybMmG+SdcgEOOg9k6+PoWxp24Q6xpvhPaZ3SXhcxVHtWOzWj3G7hAa/1t1UKibgxvzjXX0bgP3rCy2ISPmQNGnUUPd0aPc0GAXJVfCNUnTyMhQV3pooJoqBBwIbZ/L3xzecoRgP0UDnI/rFqdX1LzsfFLrXpU6Nw83nL909/3D/iHf8DDBSsJIOjPDvI4V2gAU/mDUylsK0i+C0AAGBP3IaYUwzLC9xVq8krGuaB9JoUBpLJV897DdZ4LXI5PyDomomwF8noa5aD82YmHg0SohKpRd8mgstqPlC4nZO+AE8mYq3h/DhKNRog4cCw2/rtYFmtLp7VnS1w==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgresql
        argocd.argoproj.io/instance: home-assistant
        chart: postgresql-8.9.6
        heritage: Tiller
        release: home-assistant
      name: home-assistant-postgresql
      namespace: home-assistant
    type: Opaque

