---
name: Lint

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck yamllint curl
          curl -O https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          sudo cp kubeval /usr/local/bin
      - name: Lint
        run: |
          chmod +x "$GITHUB_WORKSPACE/scripts/lint.sh"
          $GITHUB_WORKSPACE/scripts/lint.sh
